name: Flat Gothic (Dark)
author: Finn
base: colour_schemes/base_flat_dark
colours:

  toolbarNormal: "#67787d"   # main theme accent colour

  ui_listSelected: "#67787d"  # main theme accent colour

  ui_stringMatchText: "#99b3ba" # lighter version of the main theme accent colour

  ui_unselectedTextAlt: "#99b3ba" # lighter version of the main theme accent colour