name: Flat Halley
author: Finn
base: colour_schemes/base_flat
colours:

  toolbarNormal: "#fc2847"   # main theme accent colour

  ui_listSelected: "#fc2847"  # main theme accent colour

  ui_stringMatchText: "#8f0f22" # darker version of the main theme accent colour

  ui_unselectedTextAlt: "#8f0f22" # darker version of the main theme accent colour


