name: Flat Gothic
author: Finn
base: colour_schemes/base_flat
colours:

  toolbarNormal: "#67787d"   # main theme accent colour

  ui_listSelected: "#67787d"  # main theme accent colour

  ui_stringMatchText: "#36494e" # darker version of the main theme accent colour

  ui_unselectedTextAlt: "#36494e" # darker version of the main theme accent colour


