name: Flat Cobalt (Dark)
author: Finn
base: colour_schemes/base_flat_dark
colours:

  toolbarNormal: "#5c80c3"   # main theme accent colour

  ui_listSelected: "#5c80c3"  # main theme accent colour

  ui_stringMatchText: "#cadcff" # lighter version of the main theme accent colour

  ui_unselectedTextAlt: "#cadcff" # lighter version of the main theme accent colour


