name: Flat Halley (Dark)
author: Finn
base: colour_schemes/base_flat_dark
colours:

  toolbarNormal: "#fc2847"   # main theme accent colour

  ui_listSelected: "#fc2847"  # main theme accent colour

  ui_stringMatchText: "#ffaab6" # lighter version of the main theme accent colour

  ui_unselectedTextAlt: "#ffaab6" # lighter version of the main theme accent colour


