name: Flat Orange
author: Finn
base: colour_schemes/base_flat
colours:
  
  toolbarNormal: "#ff7f02"   # main theme accent colour

  ui_listSelected: "#ff7f02"  # main theme accent colour

  ui_stringMatchText: "#ab621b" # darker version of the main theme accent colour

  ui_unselectedTextAlt: "#ab621b" # darker version of the main theme accent colour