name: Flat Sakura (Dark)
author: Finn
base: colour_schemes/base_flat_dark
colours:

  toolbarNormal: "#ffb7c5"   # main theme accent colour

  ui_listSelected: "#ffb7c5"  # main theme accent colour

  ui_stringMatchText: "#ffe2e8" # lighter version of the main theme accent colour

  ui_unselectedTextAlt: "#ffe2e8" # lighter version of the main theme accent colour


backgroundParticles:
  particles:
    spawnRate: 25
    angle: 135
    angleScatter: 25
    speed: 100
    acceleration: [-10, 10]
    ttl: 10
    fadeInTime: 1
    fadeOutTime: 1
    speedDamp: 0.2
    directionScatter: 150
    rotateTowardsMovement: true
  sprites:
  - { img: halley_ui/particles_sakura_flat.png, colour: "#FFFFFF" }