name: Flat Anime
author: Finn
base: colour_schemes/base_flat_dark
colours:

  toolbarNormal: "#965fd4"   # main theme accent colour

  ui_listSelected: "#8bd450"  # main theme accent colour

  ui_stringMatchText: "#ba7dff" # lighter version of the main theme accent colour

  ui_unselectedTextAlt: "#ba7dff" # lighter version of the main theme accent colour


