name: Flat Cobalt
author: Finn
base: colour_schemes/base_flat
colours:

  toolbarNormal: "#5c80c3"   # main theme accent colour

  ui_listSelected: "#5c80c3"  # main theme accent colour

  ui_stringMatchText: "#284376" # darker version of the main theme accent colour

  ui_unselectedTextAlt: "#284376" # darker version of the main theme accent colour


