defaultColour: "#FFFFFF"
colours:
  icon_directory: "#CAA9CD"
  icon_shader: "#98D69C"
  icon_materialDefinition: "#85C5AA"
  icon_prefab: "#FBC24D"
  icon_scene: "#F08A24"
  icon_colours: "#5BF7AD"
  icon_configFile: "#5BF7AD"
  icon_localisation: "#5BF7AD"
  icon_variableTable: "#5BF7AD"
  icon_audioClip: "#4DA7EA"
  icon_audioEvent: "#5BCCF7"
  icon_font: "#707CF3"
  icon_bitmapFont: "#8073F0"
  icon_animation: "#FC7272"
  icon_image: "#FC7272"
  icon_sprite: "#FC7272"
  icon_spriteSheet: "#FC7272"
  icon_texture: "#FB4D4D"
  icon_mesh: "#FB4D4D"
  icon_meshAnimation: "#FB4D4D"
  icon_binaryFile: "#B5B9CC"
  icon_simpleCopy: "#B5B9CC"
  icon_textFile: "#B5B9CC"
  icon_movie: "#B5B9CC"

  ui_controlNormal: "#9C5BB5"
  ui_controlDown: "#913DA3"
  ui_controlHover: "#B68FCB"
  ui_controlDisabled: "#927B95"
  ui_controlNormalTransparent: "#9C5BB580"
