defaultColour: "#FFFFFF"
colours:
  icon_directory: "#CAA9CD"
  
  icon_shader: "#EC7171"
  icon_materialDefinition: "#B81616"

  icon_prefab: "#FFFF40"
  icon_scene: "#77E726"
  
  icon_colours: "#00DDE1"
  icon_configFile: "#26E743"
  icon_localisation: "#43FA52"
  icon_variableTable: "#50E9BB"
  
  icon_audioClip: "#E39343"
  icon_audioEvent: "#FFCB3E"
  
  icon_font: "#D538E9"
  icon_bitmapFont: "#D538E9"

  icon_animation: "#2457FF"
  icon_image: "#3862E9"
  icon_sprite: "#3862E9"
  icon_spriteSheet: "#7023DD"
  icon_texture: "#9D38E9"
  icon_mesh: "#9623DD"
  icon_meshAnimation: "#2457FF"
  
  icon_binaryFile: "#DEAEED"
  icon_simpleCopy: "#DEAEED"
  icon_textFile: "#AEEDBB"
  icon_movie: "#AEBFED"


  ui_controlNormal: "#9C5BB5"
  ui_controlDown: "#913DA3"
  ui_controlHover: "#B68FCB"
  ui_controlDisabled: "#927B95"
  ui_controlNormalTransparent: "#9C5BB580"

  ui_text: "#FFFFFF"
  ui_selectedText: "#FFFFFF"
  ui_unselectedText: "#FFFFFF"
  ui_textGhost: "#7F7F7F"
  ui_disabledText: "#7F7F7F"

  ui_listBackground: "#201427"
  ui_listHover: "#5E3962"
  ui_inputBox: "#9861B6"
  ui_scrollBackground: "#442947"

  ui_staticBox: "#9C5BB5"
  ui_staticBoxSubdue: "#754589"
