name: Boring Grey
defaultColour: "#FFFFFF"
colours:
  icon_directory: "#CDCDCD"
  
  icon_shader: "#EC7171"
  icon_materialDefinition: "#B81616"

  icon_prefab: "#FFFF40"
  icon_scene: "#77E726"
  
  icon_colours: "#00DDE1"
  icon_configFile: "#26E743"
  icon_localisation: "#43FA52"
  icon_variableTable: "#50E9BB"
  
  icon_audioClip: "#E39343"
  icon_audioEvent: "#FFCB3E"
  
  icon_font: "#D538E9"
  icon_bitmapFont: "#D538E9"

  icon_animation: "#2457FF"
  icon_image: "#3862E9"
  icon_sprite: "#3862E9"
  icon_spriteSheet: "#7023DD"
  icon_texture: "#9D38E9"
  icon_mesh: "#9623DD"
  icon_meshAnimation: "#2457FF"
  
  icon_binaryFile: "#DEAEED"
  icon_simpleCopy: "#DEAEED"
  icon_textFile: "#AEEDBB"
  icon_movie: "#AEBFED"
  
  
  ui_controlNormal: "#40424D"
  ui_controlDown: "#30323A"
  ui_controlHover: "#6D7285"
  ui_controlDisabled: "#191919"
  ui_controlNormalTransparent: "#40424D80"

  ui_text: "#FFFFFF"
  ui_selectedText: "#FFFFFF"
  ui_unselectedText: "#FFFFFF"
  ui_textGhost: "#7F7F7F"
  ui_disabledText: "#7F7F7F"

  ui_listBackground: "#25262E"
  ui_listSelected: "#40424D"
  ui_listHover: "#AAA5B6"
  ui_inputBox: "#86838D"
  ui_scrollBackground: "#212227"

  ui_backgroundBox: "#1E1E1E"
  ui_popupWindow: "#53131F"
  ui_staticBox: "#40424D"
  ui_staticBoxSubdue: "#30323A"

  ui_debugConsole: "#1E1E1EC0"
