name: Sakura
defaultColour: "#FFFFFF"
base: colour_schemes/default
colours:
  icon_directory: "#000000"
  
  background0: "#FFECF7"
  background1: "#FFF0F9"
  backgroundLogo: "#FFE8F5"

  ui_controlNormal: "#DD6CB6"
  ui_controlDown: "#C4398F"
  ui_controlHover: "#E796CA"
  ui_controlDisabled: "#D7AAC6"
  
  ui_buttonNormal: "#FFC6E7"
  ui_buttonDown: "#E281C0"
  ui_buttonHover: "#FFD9EF"
  ui_buttonDisabled: "#D7AAC6"

  ui_text: "#000000"
  ui_selectedText: "#000000"
  ui_unselectedText: "#000000"
  ui_disabledText: "#7F7F7F"
  ui_selectedTextAlt: "#9A570E"
  ui_unselectedTextAlt: "#9A570E"
  ui_disabledTextAlt: "#6D503A"
  ui_textGhost: "#7F7F7F"

  ui_listBackground: "#EEB5DA"
  ui_listSelected: "#FFFFFF"
  ui_listHover: "#FFC6E7"
  ui_listDrag: "#FFC6E780"

  ui_inputBox: "#DD6CB6"
  ui_inputCaret: "#000000"
  
  ui_scrollBackground: "#F8E0EF"
  ui_backgroundBox: "#F8E0EF"
  ui_popupWindow: "#FFC6E7"
  ui_staticBox: "#FFC6E7"
  ui_staticBoxSubdue: "#F9ACD5"

  ui_debugConsole: "#DD6CB6C0"

sprites:
  ui_float_window: { img: halley_ui/ui_float_window.png, material: Halley/SpriteInverseTint }
  ui_title_capsule: { img: halley_ui/ui_title_capsule.png, material: Halley/SpriteInverseTint }
  ui_input_thin: { img: halley_ui/ui_input_thin.png, material: Halley/SpriteInverseTint }
  ui_input: { img: halley_ui/ui_input.png, material: Halley/SpriteInverseTint }
  ui_checkbox: { img: halley_ui/ui_checkbox.png, material: Halley/SpriteInverseTint }
  ui_checkbox_checked: { img: halley_ui/ui_checkbox_checked.png, material: Halley/SpriteInverseTint }
  ui_dropdown_closed: { img: halley_ui/ui_dropdown_closed.png, material: Halley/SpriteInverseTint }
  ui_dropdown_open: { img: halley_ui/ui_dropdown_open.png, material: Halley/SpriteInverseTint }
  ui_dropdown_window: { img: halley_ui/ui_dropdown_window.png, material: Halley/SpriteInverseTint }
  ui_tooltip: { img: halley_ui/ui_tooltip.png, material: Halley/SpriteInverseTint }
  ui_tab_normal: { img: halley_ui/tabs/tab_normal.png, material: Halley/SpriteInverseTint }
  ui_tab_hover: { img: halley_ui/tabs/tab_hover.png, material: Halley/SpriteInverseTint }
  ui_tab_selected: { img: halley_ui/tabs/tab_selected.png, material: Halley/SpriteInverseTint }
  ui_tabs_bg: { img: halley_ui/tabs/tabs_bg.png, material: Halley/SpriteInverseTint }
