---

uiStyle:
  button:
    normal: { img: halley_ui/ui_button.png, colour: "#9C5BB5" }
    down: { img: halley_ui/ui_button.png, colour: "#913DA3" }
    hover: { img: halley_ui/ui_button.png, colour: "#B68FCB" }
    disabled: { img: halley_ui/ui_button.png, colour: "#927B95" }
    innerBorder: [ 5, 5, 5, 5 ]
    upSound: ""
    downSound: ""
    hoverSound: ""
    label: { font: Ubuntu Bold, size: 15, colour: "#FFFFFF" }
    labelBorder: [0, 0, 0, 0]
    iconBorder: [0, 0, 0, 0]

  checkbox:
    normal: { img: halley_ui/ui_checkbox.png, colour: "#9C5BB5" }
    checked: { img: halley_ui/ui_checkbox_checked.png, colour: "#9C5BB5" }
    hover: { img: halley_ui/ui_checkbox.png, colour: "#B68FCB" }
    checkedHover: { img: halley_ui/ui_checkbox_checked.png, colour: "#B68FCB" }
    disabled: { img: halley_ui/ui_checkbox.png, colour: "#CDCDCD" }
    checkedDisabled: { img: halley_ui/ui_checkbox_checked.png, colour: "#CDCDCD" }

  input:
    box: { img: halley_ui/ui_input.png, colour: "#9861B6" }
    caret: halley_ui/ui_caret.png
    innerBorder: [ 6, 5, 6, 2 ]
    label: { font: Ubuntu Regular, size: 15, colour: "#FFFFFF" }
    labelGhost: { font: Ubuntu Regular, size: 15, colour: "#7F7F7F" }
    minSize: 30

  list:
    background: { img: "halley_ui/ui_list_item.png", colour: "#201427" }
    item:
      normal: ""
      hover: { img: halley_ui/ui_list_item.png, colour: "#5E3962" }
      selected: { img: halley_ui/ui_list_item.png, colour: "#9C5BB5" }
      drag: { img: halley_ui/ui_list_item.png, colour: "#9C5BB580" }
      innerBorder: [ 6, 5, 6, 2 ]
    innerBorder: [ 0, 0, 0, 0 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    selectionChangedSound: ""
    label: { font: Ubuntu Regular, size: 15, colour: "#FFFFFFCF" }
    selectedLabel: { font: Ubuntu Regular, size: 15, colour: "#FFFFFF" }
    gap: 1

  treeList:
    background: { img: "halley_ui/ui_list_item.png", colour: "#201427" }
    item:
      normal: ""
      hover: { img: halley_ui/ui_list_item.png, colour: "#5E3962" }
      selected: { img: halley_ui/ui_list_item.png, colour: "#9C5BB5" }
      drag: { img: halley_ui/ui_list_item.png, colour: "#9C5BB580" }
      innerBorder: [ 0, 0, 0, 0 ]
    innerBorder: [ 0, 0, 0, 0 ]
    labelBorder: [ 6, 5, 6, 2 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    selectionChangedSound: ""
    label:
      normal: { font: Ubuntu Regular, size: 13, colour: "#EEEEEE" }
      selected: { font: Ubuntu Regular, size: 13, colour: "#FFFFFF" }
      disabled: { font: Ubuntu Regular, size: 13, colour: "#808080" }
    labelSpecial:
      normal: { font: Ubuntu Regular, size: 13, colour: "#E8B900" }
      selected: { font: Ubuntu Regular, size: 13, colour: "#FFCD06" }
      disabled: { font: Ubuntu Regular, size: 13, colour: "#B7A351" }
    gap: 1
    indentation: 20
    cursor:
      beforeAfter: { img: "whitebox.png" }
      over: { img: "whitebox.png", colour: "#FFFFFF80" }
    controls:
      guide_i: { img: "halley_ui/ui_treeview_line_i.png", colour: "#9C5BB5" }
      guide_t: { img: "halley_ui/ui_treeview_line_t.png", colour: "#9C5BB5" }
      guide_l: { img: "halley_ui/ui_treeview_line_l.png", colour: "#9C5BB5" }
      guide_empty: { img: "halley_ui/ui_treeview_line_i.png", colour: "#00000000" }
      leaf: { img: "halley_ui/ui_treeview_leaf.png", colour: "#9C5BB5" }
      element: { img: "halley_ui/ui_treeview_element.png", colour: "#FFFFFF" }
      collapseButton:
        normal: { img: halley_ui/ui_treeview_expanded.png, colour: "#9C5BB5" }
        down: { img: halley_ui/ui_treeview_expanded.png, colour: "#913DA3" }
        hover: { img: halley_ui/ui_treeview_expanded.png, colour: "#B68FCB" }
        disabled: { img: halley_ui/ui_treeview_expanded.png, colour: "#927B95" }
        innerBorder: [ 0, 0, 0, 0 ]
        upSound: ""
        downSound: ""
        hoverSound: ""
        label: { font: Ubuntu Regular, size: 13, colour: "#FFFFFF" }
        labelBorder: [0, 0, 0, 0]
      expandButton:
        normal: { img: halley_ui/ui_treeview_collapsed.png, colour: "#9C5BB5" }
        down: { img: halley_ui/ui_treeview_collapsed.png, colour: "#913DA3" }
        hover: { img: halley_ui/ui_treeview_collapsed.png, colour: "#B68FCB" }
        disabled: { img: halley_ui/ui_treeview_collapsed.png, colour: "#927B95" }
        innerBorder: [ 0, 0, 0, 0 ]
        upSound: ""
        downSound: ""
        hoverSound: ""
        label: { font: Ubuntu Regular, size: 13, colour: "#FFFFFF" }
        labelBorder: [0, 0, 0, 0]

  dropdown:
    normal: { img: halley_ui/ui_dropdown_closed.png, colour: "#9C5BB5" }
    hover: { img: halley_ui/ui_dropdown_closed.png, colour: "#B68FCB" }
    open: { img: halley_ui/ui_dropdown_open.png, colour: "#B68FCB" }
    disabled: { img: halley_ui/ui_dropdown_closed.png, colour: "#CDCDCD" }
    background: { img: halley_ui/ui_dropdown_window.png, colour: "#B68FCB" }
    innerBorder: [ 2, 2, 2, 2 ]
    labelBorder: [ 6, 8, 0, 0 ]
    label: { font: Ubuntu Regular, size: 15, colour: "#FFFFFF" }
    selectedLabel: { font: Ubuntu Regular, size: 15, colour: "#FFFFFF" }
    openSound: ""
    closeSound: ""
    height: 200
    minSize: 30
    minSizeMargins: [ 40, 20, 0, 0 ]

  scrollbar:
    bar:
      horizontal: { img: halley_ui/ui_scrollbar.png, colour: "#5E3962" }
      vertical: { img: halley_ui/ui_scrollbar.png, colour: "#5E3962" }
    up:
      normal: { img: halley_ui/ui_scrollbar.png, colour: "#9C5BB5" }
      disabled: { img: halley_ui/ui_scrollbar.png, colour: "#8D7B95" }
      down: { img: halley_ui/ui_scrollbar.png, colour: "#913DA3" }
      hover: { img: halley_ui/ui_scrollbar.png, colour: "#B68FCB" }
      innerBorder: [ 3, 3, 3, 3 ]
      upSound: ""
      downSound: ""
      hoverSound: ""
    down:
      normal: { img: halley_ui/ui_scrollbar.png, colour: "#9C5BB5" }
      disabled: { img: halley_ui/ui_scrollbar.png, colour: "#8D7B95" }
      down: { img: halley_ui/ui_scrollbar.png, colour: "#913DA3" }
      hover: { img: halley_ui/ui_scrollbar.png, colour: "#B68FCB" }
      innerBorder: [ 3, 3, 3, 3 ]
      upSound: ""
      downSound: ""
      hoverSound: ""
    left:
      normal: { img: halley_ui/ui_scrollbar.png, colour: "#9C5BB5" }
      disabled: { img: halley_ui/ui_scrollbar.png, colour: "#8D7B95" }
      down: { img: halley_ui/ui_scrollbar.png, colour: "#913DA3" }
      hover: { img: halley_ui/ui_scrollbar.png, colour: "#B68FCB" }
      innerBorder: [ 3, 3, 3, 3 ]
      upSound: ""
      downSound: ""
      hoverSound: ""
    right:
      normal: { img: halley_ui/ui_scrollbar.png, colour: "#9C5BB5" }
      disabled: { img: halley_ui/ui_scrollbar.png, colour: "#8D7B95" }
      down: { img: halley_ui/ui_scrollbar.png, colour: "#913DA3" }
      hover: { img: halley_ui/ui_scrollbar.png, colour: "#B68FCB" }
      innerBorder: [ 3, 3, 3, 3 ]
      upSound: ""
      downSound: ""
      hoverSound: ""
    thumb:
      normal: { img: halley_ui/ui_scrollbar.png, colour: "#9C5BB5" }
      down: { img: halley_ui/ui_scrollbar.png, colour: "#913DA3" }
      hover: { img: halley_ui/ui_scrollbar.png, colour: "#B68FCB" }
      innerBorder: [ 3, 3, 3, 3 ]
      upSound: ""
      downSound: ""
      hoverSound: ""

  label:
    label: { font: Ubuntu Bold, size: 15, colour: "#FFFFFF" }

  tooltip:
    background: { img: halley_ui/ui_tooltip.png, colour: "#5E3962" }
    innerBorder: [ 5, 5, 5, 5 ]
    delay: 0.3
    maxWidth: 200
    label: { font: Ubuntu Bold, size: 14, colour: "#FFFFFF" }

  labelLight:
    label: { font: Ubuntu Light, size: 14, colour: "#FFFFFF" }

  inputThin:
    box: { img: halley_ui/ui_input_thin.png, colour: "#9861B6" }
    caret: halley_ui/ui_caret.png
    innerBorder: [ 6, 3, 6, 2 ]
    label: { font: Ubuntu Light, size: 14, colour: "#FFFFFF" }
    labelGhost: { font: Ubuntu Light, size: 14, colour: "#7F7F7F" }
    minSize: 22

  buttonThin:
    normal: { img: halley_ui/ui_button.png, colour: "#9C5BB5" }
    down: { img: halley_ui/ui_button.png, colour: "#913DA3" }
    hover: { img: halley_ui/ui_button.png, colour: "#B68FCB" }
    disabled: { img: halley_ui/ui_button.png, colour: "#927B95" }
    innerBorder: [ 5, 0, 5, 1 ]
    upSound: ""
    downSound: ""
    hoverSound: ""
    label: { font: Ubuntu Bold, size: 14, colour: "#FFFFFF" }
    labelBorder: [0, 0, 0, 0]

  slider:
    emptyBar: halley_ui/slider_bar_empty.png
    fullBar: halley_ui/slider_bar_full.png
    left: halley_ui/slider_bar_left.png
    right: halley_ui/slider_bar_right.png
    thumb: halley_ui/slider_thumb.png
    labelBorder: { img: whitebox.png, colour: "#FFFFFF00" }
    innerBorder: [3, 0, 2, 0]
    barBorder: [0, 1, 6, 1]
    labelInnerBorder: [2, 0, 2, 0]
    extraMouseBorder: [1, 3, 1, 3]
    label: { font: Ubuntu Bold, size: 14, colour: "#FFFFFF" }

  tabs:
    background: { img: halley_ui/tabs/tabs_bg.png, colour: "#9C5BB5" }
    item:
      normal: { img: halley_ui/tabs/tab_normal.png, colour: "#9C5BB5" }
      hover: { img: halley_ui/tabs/tab_hover.png, colour: "#9C5BB5" }
      selected: { img: halley_ui/tabs/tab_selected.png, colour: "#9C5BB5" }
      disabled: { img: halley_ui/tabs/tab_normal.png, colour: "#9C5BB5" }
      innerBorder: [ 5, 6, 5, 2 ]
    innerBorder: [ 10, 0, 10, 0 ]
    extraMouseBorder: [ 0, 0, 0, 0 ]
    label: { font: Ubuntu Bold, size: 14, colour: "#DDDDDD" }
    selectedLabel: { font: Ubuntu Bold, size: 14, colour: "#FFFFFF" }
    disabledLabel: { font: Ubuntu Bold, size: 14, colour: "#808080" }
    selectionChangedSound: ""
    gap: 1

...