---
widget: { class: widget }
sizer: { type: vertical }
children:
- widget:
    class: list
    id: assetType
    type: horizontal
    options:
    - id: sprite
      text: Sprites
    - id: animation
      text: Animations
    - id: texture
      text: Textures
    - id: audioClip
      text: Audio Clips
    - id: audioEvent
      text: Audio Events
    - id: font
      text: Fonts
    - id: materialDefinition
      text: Materials
    - id: shader
      text: Shaders
- widget: { class: widget }
  proportion: 1
  border: [0, 10, 0, 0]
  sizer: { type: horizontal }
  children:
  - sizer: { type: vertical }
    children:
    - widget: { id: assetSearch, class: textInput, size: [ 40, 30 ], ghost: "Search assets..." }
      border: [0, 0, 0, 5]
    - widget: { class: scrollBarPane }
      proportion: 1
      children:
      - widget: 
          class: list
          id: assetList
          size: [250, 20]
          options:
          - id: test0
            text: test
          - id: test1
            text: test
          - id: test2
            text: test
    - sizer: { type: horizontal }
      children:
        - widget: { id: addAsset, class: button, text: Add }
          proportion: 1
        - widget: { id: removeAsset, class: button, text: Remove }
          proportion: 1
  - widget: { class: assetEditor }
    proportion: 1
    border: [10, 0, 10, 0]
  - sizer: { type: vertical }
    children:
    - widget: { class: metadataEditor }
    - widget: { id: openFile, class: button, text: Open File }
    - widget: { id: showFile, class: button, text: Show File }
...