---
widget: { class: image, image: "halley_ui/title_capsule.png", innerBorder: [ 4, 1, 4, 4 ], colour: ui_staticBoxSubdue }
sizer: { type: vertical }
children:
- widget: { id: fieldName, class: label, text: "Name" }
  fill: centre
- widget: { id: fields, class: widget }
  border: [1, 4, 1, 1]
  sizer: { type: vertical, gap: 2 }
...